services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APACHE_CONF: ${APACHE_CONF}
        APP_ENV: ${APP_ENV}
    container_name: BLOC-5${APP_ENV}
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html/public
    depends_on:
      - db
    env_file:
      - ${ENV_FILE}

  db:
    image: mysql:8
    container_name: BLOC-5${APP_ENV}
    restart: always
    env_file:
      - ${ENV_FILE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data_${APP_ENV}:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql

volumes:
  db_data_dev:
  db_data_prod: