services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APACHE_CONF: ${APACHE_CONF}
        APP_ENV: ${APP_ENV}
    container_name: bloc5-web-${APP_ENV}
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    env_file:
      - ${ENV_FILE}
  db:
    image: mysql:8
    container_name: bloc5-db-${APP_ENV}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data_${APP_ENV}:/var/lib/mysql
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql

volumes:
  db_data_dev:
  db_data_prod: